/**
 * SDK version, inlined at build time.
 *
 * This file is generated by `scripts/sync-version.mjs` from package.json and is
 * checked in so type-checking and tests work without a build step. Do not edit
 * it by hand — `bun run build` and `changeset version` both regenerate it, and
 * a test asserts it matches package.json.
 *
 * It exists because the previous `process.env.npm_package_version` read was
 * wrong twice over: npm only sets that variable for its own lifecycle scripts,
 * so it was always undefined for consumers, and the bare `process` reference
 * survived bundling and threw a ReferenceError in browsers.
 */
export const SDK_VERSION = "0.3.1"
